


[[session]]
name = "home"
path = "~"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "zsh config"
path = "~/.config/zsh"
startup_command = "nvim ."

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim . -c ':Telescope find_files'"

[[session]]
name = "kitty config"
path = "~/.config/kitty"
startup_command = "nvim kitty.conf"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "downloads"
path = "~/downloads"
startup_command = "lf"

[[session]]
name = "SSH create connection"
path = "~/remote"
startup_command = "var_ssh=$(cat ~/.ssh/config | rg 'Host ' | awk '{print $2}' | fzf); tmux rename-session 'SSH '$var_ssh; clear; ssh $var_ssh; unset var_ssh"
