
#colors
palette = "cyberdream"

format = """
$hostname$directory$git_branch$git_status$lua$nodejs$memory_usage$php$golang$package$python$rust\
$fill$jobs\
$line_break\
$character"""



[fill]
symbol =" "

[username]
style_user = "cmain1"
style_root = "cmain2"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](cmain2) [>> ](cmain3)'
trim_at = "."
disabled = false

[time]
disabled = false
format = "[$time](coff2)"

[character]
success_symbol ="[󰣇](cres1)"
error_symbol = "[󰯆](cres2)"
vimcmd_symbol = "[](cres3)"

# configure directory
[directory]
home_symbol = "~"
read_only = " 󰌾"
read_only_style = "cres2"
truncation_length = 10
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "cdir"


[jobs]
symbol = ""
style = "cres2"
number_threshold = 1
format = "[$symbol]($style) "


# [docker_context]
# symbol = " "
# format = "via [$symbol$context]($style) "
# style = "blue bold"
# only_with_files = true
# detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
# detect_folders = []
# disabled = false


[git_branch]
symbol = " "
format = "[on ](cmain3)[$symbol$branch(:$remote_branch)](cgit) "

[git_status]
format = "[$all_status$ahead_behind](cgit)"

[nodejs]
format = "(cmain3) [ Node.js $version](cenv) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[lua]
format = "[via](cmain3) [ Lua $version](cenv)"

[memory_usage]
symbol = "󰍛 "
format = "[$symbol !!! starship](cres2)"

[php]
symbol = " "
format = "[via](cmain3) [ PHP $version](cenv)"

[golang]
symbol = " "
format = "[via](cmain3) [ GO $version](cenv)"

[package]
symbol = " "
format = "[$symbol !!! starship](cres2)"


[python]
symbol = " "
format = "[$symbol !!! starship](cres2)"


[rust]
symbol = " "
format = "[$symbol !!! starship](cres2)"



#colors

[palettes.cyberdream]
cmain3 = "#ff5ea0"
cmain2 = "#5ea1ff"
cmain1 = "#5ea1ff"

cdir = "#5eff6c"

cres1 = "#f1ff5e"
cres2 = "#ff6e5e"
cres3 = "#bd5eff"

cgit = "#5ef1ff"
cenv = "#f1ff5e"


coff2 = "#7b8496"
coff1 = "#3c4048"

[palettes.tokyonight]
cmain3 = "#65bcff"
cmain2 = "#82aaff"
cmain1 = "#3e68d7"

cdir = "#b4f9f8"

cres1 = "#ffc777"
cres2 = "#ff757f"
cres3 = "#c3e88d"

cgit = "#ff966c"
cenv = "#ffc777"


coff1 = "#494d64"
coff2 = "#363a4f"

[palettes.dracula]
orange = "#ffb86c"
green = "#50fa7b"
red = "#ff5555"
yellow = "#f1fa8c"
pink = "#ff79c6"
purple = "#bd93f9"
blue = "#8be9fd"

cmain1 = "#50fa7b"
cmain2 = "#bd93f9"
cmain3 = "#ff79c6"

cdir = "#f1fa8c"

cres1 = "#f1fa8c"
cres2 = "#ff5555"
cres3 = "#50fa7b"


cenv = "#8be9fd"
cgit = "#ff79c6"


coff1 = "#494d64"
coff2 = "#363a4f"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

cmain1 = "#c6a0f6"
cmain2 = "#f5bde6"
cmain3 = "#b7bdf8"

cdir = "#f5bde6"

cres1 = "#f4dbd6"
cres2 = "#ee99a0"
cres3 = "#a6da95"


cgit = "#f5a97f"
cenv =  "#eed49f"


coff1 = "#494d64"
coff2 = "#363a4f"

